name:  Check code quality
on:
  pull_request:
    branches: [ main, develop ]
jobs:
  code_quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: subosito/flutter-action@master
        with:
         flutter-version: '1.26.x'
         channel: 'dev'
      - run: flutter analyze